[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://digital-product-selling.netlify.app"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
